SHOP/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls

from SHOP import settings
from magazine.views import products_all, ProductDetailView, products_cat, SignUpView, profile, \
    edit_product, SearchResponceList, AddComment, RespondComment, post, DeleteProduct

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',products_all , name = 'home'),
    path('categories/<slug:cat_slug>',products_cat,name='category'),
    path('product/<slug:product_slug>',ProductDetailView.as_view(),name='product'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/<int:user_id>/', profile, name='profile'),
    path('add/',post,name='add_product'),
    path('edit/<int:prod_id>',edit_product,name='edit_product'),
    path('search/',SearchResponceList.as_view(),name = 'search'),
    path('review/<int:id>',AddComment.as_view(),name='add_review'),
    path('delete/<int:product_id>',DeleteProduct.as_view(),name='delete_product'),
    path('review/<int:prod_id>/<int:com_id>',RespondComment.as_view(),name='respond_review'),
]

if settings.DEBUG:
    urlpatterns = [
        # ...
        path("__debug__/", include("debug_toolbar.urls")),
    ]+urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazine/models.py
from django.contrib.auth.models import  AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from django.core.exceptions import ValidationError
import uuid


# create path in media for images special for uniq users
def user_directory_path(instance,filename):
    return f'user_{0}/{1}'.format(instance.owner.username,filename)

# create path in media for images special for products (if delete error )
def product_images_path(instance,filename):
    return f'product_{0}/{1}'.format(instance.product.title,filename)


# create path in media for images in ProductImages model
def get_image_filename(instance, filename):
    title = instance.post.title
    slug = slugify(title)
    return "post_images/%s-%s" % (slug, filename)

# generation uniq slug for models in  custom save() method (Product model upper)
def generate_unique_slug(title):
     base_slug = slugify(title)
     unique_id = str(uuid.uuid4())[:8]  # Возьми первые 8 символов из UUID (модуль для помощи создания уникальных слагов)
     return f'{base_slug}-{unique_id}'

# model for each Product
class Product(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.SlugField(max_length=250,unique=True,db_index=True)
    img = models.ImageField(verbose_name='Главное изображение',upload_to='img/%Y-%m-%d/',blank=True, null=True)
    owner = models.ForeignKey('CustomUser',on_delete=models.CASCADE)
    status_have = models.BooleanField(default=True)
    cat = models.ForeignKey('Category',on_delete=models.CASCADE)
    price = models.IntegerField( validators=[
            MinValueValidator(100),
        ],verbose_name='Цена')
    discount = models.IntegerField( validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],blank=True,null=True,verbose_name='Скидка в процентах')
    discounted_price = models.IntegerField(blank=True,null=True, verbose_name='Экономия')
    sell_price = models.IntegerField(blank=True,null=True,verbose_name='цена со скидкой')

    @property
    def discounted_price(self):
        return ((self.price) * (self.discount)) / 100

    @property
    def sell_price(self):
        return (self.price) - (self.discounted_price)


    # если пользователь не загрузил картинку то вместо нее будет картинка из инета нейтральная
    @property
    def img_url(self):
        if self.img and hasattr(self.img,'url'):
            return self.img.url
        else:
            return 'https://pskovokb.ru/templates/yootheme/cache/4c/no-phono-4c3d352d.jpeg'



    # create uniq slag for each product
    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = generate_unique_slug(self.title) # здесь используется функция которую мы написали над моделью Product
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('product', kwargs={'product_slug': self.slug})




# модель для добавления дополнительных изображений к нашим товарам
class ProductImage(models.Model):
    post = models.ForeignKey(Product, on_delete=models.CASCADE,related_name='images')
    img = models.ImageField(verbose_name='Дополнительное Изображение',upload_to=get_image_filename)
    # используется уникальный путь который мы прописали для медиа файлов выше




    class Meta:
        verbose_name= 'фото товара'
        verbose_name_plural = 'фото товара'

class Category(models.Model):
    parent_category=models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=20,verbose_name='cat_name')
    slug = models.SlugField(max_length=20,unique=True,db_index=True)

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = generate_unique_slug(self.name)  # здесь тоже используется функция для генерации уникальных слагов
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

# Пользоватьель с картинкой и полями для Имени , Фамилии и Емайла
class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to=f'avatar/%Y/%m/%d',blank=True, null=True)

    def __str__(self):
        return self.username


    # Если пользователь не загружает картинку то мы берем ее поумолчанию из интернета
    def avatar_url(self):
        if self.avatar and hasattr(self.avatar,'url'):
            return self.avatar.url
        else :
            return 'https://pic.onlinewebfonts.com/svg/img_165779.svg'

    @property
    def get_absolute_url(self):
        return reverse('profile', kwargs={'user_id': self.id})



# модель для создания комментариев
class Comment(models.Model):

    responce = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='response')
    # responce поле это поле для ответа на другой комментарий и таким образом формируется связь между двумя экземплярами одной модели


    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='comments')
    text = models.TextField('комментарий')
    date = models.DateTimeField(auto_now=True)

    class CommentManager(models.Manager):
        def all(self):
            """
            Список статей (SQL запрос с фильтрацией для страницы списка статей)
            """
            all= self.get_queryset().select_related('author', 'product').all()

            return all.prefetch_related('responce')

magazine/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Product, Comment, ProductImage
from django.db import models


class ProductCreate(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['cat'].empty_label = 'Не выбрано'


    class Meta:
        model = Product
        fields = ('title','status_have','description','cat','price','discount','img')


class ImageForm(forms.ModelForm):

    class Meta:
        model = ProductImage
        fields = ('img', )

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username','avatar','first_name','last_name')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username','avatar')

class AddCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

magazine/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, CreateView, ListView
from .forms import CustomUserCreationForm, AddCommentForm, ImageForm, ProductCreate
from django.forms import modelformset_factory
from django.db.models import Q, Count
# Create your views here.

from .models import *



# показать все посыт
def products_all(request):
    model = Product.objects.select_related('owner').all()
    categories = Category.objects.filter(parent_category=None)
    context = {
        'products': model,
        'categories': categories,
    }
    return render(request,'product_list.html',context)




'''показать посты для категории'''
def products_cat(request,cat_slug):
    model = Product.objects.filter(Q(cat__slug=cat_slug) | Q(cat__parent_category__slug=cat_slug)).select_related('owner')
    categories = Category.objects.filter(parent_category=None)
    cat_selected = Category.objects.get(slug=cat_slug)
    context = {
        'products':model,
        'categories': categories,
        'cat_selected':cat_selected,
               }
    return render(request,'product_list.html',context)




'''показать страницу для определенного поста'''
class ProductDetailView(DetailView):
    model = Product
    template_name = 'detail.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.filter(parent_category=None)
        comments = Comment.objects.filter(product = self.object).prefetch_related('response','response__author')
        context['comments'] = comments.select_related('author','product','responce')
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('owner','cat')

        return queryset



'''страница регистрации с формой и переодрессацией после регистрациии'''
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'





'''страница для редактирования постов'''
@login_required
def edit_product(request,prod_id):
    ImageFormSet = modelformset_factory(ProductImage, ImageForm, extra=3)

    product = get_object_or_404(Product,id=prod_id)
    if request.method == 'POST':
        post_form = ProductCreate(request.POST,request.FILES,instance=product)
        formset = ImageFormSet(request.POST,request.FILES,queryset=ProductImage.objects.none())
        if post_form.is_valid() and formset.is_valid():
            post_form.save()
            for form in formset:
                if form.is_valid():
                    if 'img' in form.cleaned_data:
                        image = form.cleaned_data['img']
                        if image:
                            photo = ProductImage(post=product, img=image)
                            photo.save()


            return HttpResponseRedirect(product.get_absolute_url())
    else:
        post_form = ProductCreate(instance=product)
        formset = ImageFormSet(queryset=ProductImage.objects.none())
    context = {'postForm':post_form,'formset':formset,'title':"Обновить",}
    return render(request,'add_product.html',context)






'''страница с профилем'''
def profile(request,user_id):
    profile = CustomUser.objects.get(id=user_id)
    products = Product.objects.select_related('owner').filter(owner=profile)
    return render(request,'profile.html',{'profile':profile,'products':products})





'''отвечает за поиск постов по заголовку'''
class SearchResponceList(ListView):
    template_name = 'product_list.html'
    context_object_name = 'products'
    """Поиск по названию товара"""

    def get_queryset(self):
         return Product.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['categories']  = Category.objects.filter(parent_category=None)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context





'''добавить комментарий'''
class AddComment(View):
    def post(self,request,id):
        form = AddCommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.product_id = id
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class DeleteProduct(View):
    def post(self,request,product_id):
        post = Product.objects.get(id = product_id)
        if request.method == 'POST':
            post.delete()
            return redirect('/')



'''ответить на комментарий'''
class RespondComment(View):
    def post(self,request,prod_id,com_id):
        form = AddCommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.product_id = prod_id
            form.responce_id = com_id
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



# отправка формы о создании поста
@login_required
def post(request):
    ImageFormSet = modelformset_factory(ProductImage,ImageForm,extra=3,can_delete=True)

    if request.method == 'POST':
        postform = ProductCreate(request.POST,request.FILES or None)
        formset = ImageFormSet(request.POST,request.FILES,queryset=ProductImage.objects.none())

        if postform.is_valid() and formset.is_valid():
            post_form =  postform.save(commit=False)
            post_form.owner = CustomUser.objects.get(id=request.user.id)
            post_form.save()

            for form in formset:
                if form.is_valid():
                    if 'img' in form.cleaned_data:
                        image = form.cleaned_data['img']
                        if image:
                            photo = ProductImage(post=post_form, img=image)
                            photo.save()
            messages.success(request,'Все данные были добавлены и вы успешно создали товар!')
            return HttpResponseRedirect('/')
        else:
            print(postform.errors, formset.errors)

    else:
        postform = ProductCreate()
        formset = ImageFormSet(queryset=ProductImage.objects.none())

    return render(request,'add_product.html',{'postForm':postform,'formset':formset})


@login_required
def delete_post(request, product_slug):
    product = get_object_or_404(Product, id=product_slug, author=request.user)

    if request.method == 'POST':
        product.delete()
        return redirect('post_list')  # Перенаправляем на список постов после удаления

    return render(request, 'delete_post.html', {'product': product})

magazine/templates/add_product.html
{% extends 'base.html' %}
    {% load crispy_forms_tags %}

{% block content %}
<h2>{{title}}</h2>
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in postForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {{postForm | crispy}}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form | crispy}} <br>
    {% endfor %}


    <input type="submit" name="submit" value="Submit" />
</form>
{% endblock %}

<!--
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy}}
    <div class=""><input type="file" name="photos" multiple></div>
  <button type="submit">Отправить</button>
</form>
-->

magazine/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link rel="stylesheet"  type="text/css" href="{% static 'css/static.css' %}" />
    <link rel="stylesheet"  type="image/png" href="{% static 'vizbran.png' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">InternetShop</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'home' %}"
                >Все товары</a
              >
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
              <a class="nav-link" href="{% url 'add_product' %}">Продать</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{user.get_absolute_url}}">{{user}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Вход</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Регистрация</a>
            </li>
            {% endif %}
          </ul>
      <form action="{% url 'search' %}" class="d-flex" method="get">
        <input class="form-control me-2" type="search"  name="q" placeholder="Название товара..." aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        </div>

      </div>

    </nav>
    <div class="container">
      <div class="row">
        <div class="col-2">
          {% block cats %}
          {% endblock %}

        </div>
        <div class="col-10">

          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

magazine/templates/detail.html
{% extends 'base.html' %} {% block cats %}
<ul class="list-group list-group-flush">
  {% for cat in categories %}
  <li class="list-group-item">
    <a href="{{cat.get_absolute_url}}">{{cat.name}}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %} {% block content %}

<div class="product-detail">
  <div class="container detail_image my-4">
    <div id="carouselExampleDark" class="carousel carousel-dark slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img
            src="{{product.img_url}}"
            class="d-block"
            alt="Картинка товара"
          />
        </div>
        {% for img in product.images.all %}
        <div class="carousel-item">
          <img src="{{img.img.url}}" class="d-block" alt="Изображение" />
        </div>
        {% endfor %}
      </div>

      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleDark"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleDark"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

<div class="detail_info">
  <div class="orange_buttons">
    <p>
      {% if product.owner == request.user %}
      <a class href="{% url 'edit_product' product.id %}"
        ><img
          class="edit_button_detail"
          src="https://cdn4.iconfinder.com/data/icons/basic-interface-overcolor/512/pencil-1024.png"
          alt="edit"
      /></a>
      <!-- Button trigger modal -->
<button type="button" class="btn" data-toggle="modal" data-target="#exampleModal">
  <img class="edit_button_detail" src="https://cdn4.iconfinder.com/data/icons/social-messaging-ui-color-and-shapes-4/177800/175-1024.png" alt="">
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <h5 class="modal-title" id="exampleModalLabel">Удалить Товар</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Вы уверены что хотите удалить {{product.title}} ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отменить</button>
        <form action="{% url 'delete_product' product.id %}" method="post">
        {% csrf_token %}
          <button type="submit" class="btn btn-warning">Удалить</button>
    </form>

      </div>
    </div>
  </div>
</div>

      {% endif %}
    </p>
    <div class="previouse">
      <a href="{{request.META.HTTP_REFERER}}"
        ><img
          width="70px"
          src="https://cdn3.iconfinder.com/data/icons/arrows-25/137/Left-08-1024.png"
          alt=""
      /></a>
    </div>
    
  </div>

  <h3 class="my-3">{{product.title}}</h3>
  <h4>
    Продавец :<a style="color: orange" href="{{product.owner.get_absolute_url}}"
      >{{product.owner}}</a
    >
  </h4>
  {% if product.discount %}
  <p class="active-detail">{{product.sell_price}} тг <span class="no-active-detail">{{product.price}} тг</span></p>
  {% else %}
   <p class="active-detail">{{product.price}} тг</p>
  {% endif %}
  <p>{{product.description | linebreaks }}</p>

  <p>Рейтинг : 4.9</p>
  <p>
    <a href="#">В корзину</a> <a href="#">Купить</a> <a href="#">В избранное</a>
  </p>
</div>
<div class="comments_block px-5 container mt-5 mb-5">
  <div class="form window">
    <h3>Комментарии ({{product.comments.all.count}})</h3>
    <form action="{% url 'add_review' product.id %}" method="post">
      {% csrf_token %}
      <label for="exampleFormControlTextarea1" class="form-label"
        >Написать комментарий</label
      >
      <textarea
        class="d-flex form-control"
        id="exampleFormControlTextarea1"
        rows="3"
        name="text"
      ></textarea>
      <button type="submit" class="btn btn-primary mt-3 mb-3">Отправить</button>
    </form>
  </div>

  <div class="user_comments">
    {% for com in comments %}
    {% if com.responce is None %}
    <div class="comment-item my-4">
      <div class="row">
        <div class="col-1 com_img">
          <img src="{{com.author.avatar_url}}" alt="avatar" />
        </div>
        <div class="col-11 com_text">
          <p>
            <a href="{{com.author.get_absolute_url}}">{{com.author}}</a>,
            {{com.date}}{% if com.responce %},<span
              >ответ для {{com.responce.author}}</span
            >
            {% endif %}
          </p>
          <p>{{com.text}}</p>
          <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button
                  class="accordion-button collapsed"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseOne{{com.id}}"
                  aria-expanded="false"
                  aria-controls="flush-collapseOne{{com.id}}"
                >
                  Ответить
                </button>
              </h2>
              <div
                id="flush-collapseOne{{com.id}}"
                class="accordion-collapse collapse"
                data-bs-parent="#accordionFlushExample"
              >
                <div class="accordion-body">
                  <form action="{% url 'respond_review' product.id com.id %}" method="post">
                    {% csrf_token %}
                    <textarea
                      class="d-flex form-control"
                      rows="1"
                      name="text"
                    ></textarea>
                    <button type="submit" class="btn btn-primary mt-3 mb-3">
                      Отправить
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% for responced in com.response.all %}
    <div class="comment-item my-4 px-5 mx-3">
      <div class="row">
        <div class="col-1 com_img">
          <img src="{{responced.author.avatar_url}}" alt="avatar" />
        </div>
        <div class="col-11 com_text">
          <p>
            <a href="{{responced.author.get_absolute_url}}">{{responced.author}}</a>,
            {{responced.date}}{% if responced.responce %},<span
              >ответ для {{responced.responce.author}}</span
            >
            {% endif %}
          </p>
          <p>{{responced.text}}</p>
          <div class="accordion accordion-flush" id="accordionFlushExampleresponced">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button
                  class="accordion-button collapsed"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#flush-collapseOne{{responced.id}}"
                  aria-expanded="false"
                  aria-controls="flush-collapseOne{{responced.id}}"
                >
                  Ответить
                </button>
              </h2>
              <div
                id="flush-collapseOne{{responced.id}}"
                class="accordion-collapse collapse"
                data-bs-parent="#accordionFlushExampleresponced"
              >
                <div class="accordion-body">
                  <form action="{% url 'respond_review' product.id responced.id %}" method="post">
                    {% csrf_token %}
                    <textarea
                      class="d-flex form-control"
                      rows="1"
                      name="text"
                    ></textarea>
                    <button type="submit" class="btn btn-primary mt-3 mb-3">
                      Отправить
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
      </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

magazine/templates/product_list.html
{% extends 'base.html' %}

      {% block cats %}

 <ul class="list-group list-group-flush">
   {% for cat in categories %}
     {% if cat == cat_selected %}
              <li class="list-group-item">{{cat.name}}</li>
                    <ul class="list-group list-group-flush dop">
                         {% for subcategory in cat.category_set.all %}
                        <li class="list-group-item"><a href="{{subcategory.get_absolute_url}}">{{subcategory}}</a></li>
                        {% endfor %}
            </ul>
     {% else %}
      <li class="list-group-item"><a href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
     {% endif %}
   {% endfor %}
          </ul>
          {% endblock %}


{% block content %}
 <div class="products">
            <div class="row">
                {% for product in products %}

              <div class="col-3 my-3">
                <div class="card">
                    {% if product.owner == request.user %}
                <a class href="{% url 'edit_product' product.id %}"><img class="edit_button" src="https://cdn4.iconfinder.com/data/icons/basic-interface-overcolor/512/pencil-1024.png" alt="edit"></a>
                {% endif %}
                  <a href=""><img class="favorite_button" src="https://cdn4.iconfinder.com/data/icons/essential-collection/54/bookmark-1024.png" alt="image"></a>
                  <a href="{{product.get_absolute_url}}">
                      <img src="{{ product.img_url|default_if_none:'#' }}" class="card-img-top" alt="image">
                  </a>
                  <div class="card-body">
                    <h5 class="card-title">{{product.title|truncatewords:3}}</h5>
                      {%if product.discount%}
                    <p class="card-text"><span class="active">{{product.sell_price}} тг</span>
                        <span class="no-active">{{product.price}}тг</span></p>
                      {% else %}
                       <p class="card-text"><span class="active">{{product.price}} тг</span>
                      {% endif %}
                    <p class="card-text"><a href="#" class="btn btn-primary">В корзину </a><span>(на складе)</span></p>

                  </div>
                </div>
              </div>
                {% endfor %}
          </div>
 </div>
{% endblock%}